version: '2'
services:
  selenium-hub:
    image: selenium/hub
    container_name: "selenium-hub"
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    container_name: "node-chrome"
    environment:
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"
    expose:
      - 5555
    depends_on:
      - selenium-hub
  firefox:
    image: selenium/node-firefox
    container_name: "node-firefox"
    environment:
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"
    expose:
      - 5555
    depends_on:
      - selenium-hub
